### ISSUE TITLE
[BUG] "ITEM.TypeWeaponPl" is shown as header under inventory category

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#10]
**Describe the bug**
<img width="541" alt="image" src="https://user-images.githubusercontent.com/72390280/214866534-74bf2509-00cc-4bb4-8b56-8f5bc0385b1b.png">

**Versions:**
Token Action HUD Core: 1.01
Token Action HUD System: token-action-hud-dnd5e 1.01
System: dnd5e 2.0.3
Foundry VTT: 10.291
Browser: Google Chrome 109.0.5414.119

**Comment by Larkinabout** [comment]
I retroactively changed the minimum compatibility to dnd5e 2.1.0 as that update changed some of the language references that Token Action HUD uses. When you update to 2.1.0+, you can fix it by removing the subcategory then adding it back in from the subcategory list.

In the meantime, you should be able to go into the subcategory dialog, double-click on the name and rename it to something else. Just be aware that it will only keep the name for that instance, so removing and adding will revert it back to the broken reference.
