### ISSUE TITLE
[FEATURE] Please support DnD5e enrichers in HUD tooltip

### ISSUE THREAD

**Issue by ctbritt** [Larkinabout/fvtt-token-action-hud-dnd5e#102]
**Describe your idea**
When the tool tips pop up, they correctly read the enricher codes from the description field on the item.

**Versions**
- Token Action HUD System: token-action-hud-dnd5e
- System: DnD5e

**Additional context**
![CleanShot 2024-06-15 at 15 04 12](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/4516034/ee22aa7a-02d1-49f0-a625-3ef8baf81eb1)
![CleanShot 2024-06-15 at 15 05 31](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/4516034/14c762b0-e7af-46b3-9683-68e5a9bfe449)

**Comment by Larkinabout** [comment]
Added in 1.5.8.
