### ISSUE TITLE
[FEATURE] Enable display of (secret) paragraph text for creature attacks

### ISSUE THREAD

**Issue by brother-oak** [Larkinabout/fvtt-token-action-hud-dnd5e#103]
In the DnD 5e SRD compendium, as well as other places, the "useful" information about an attack (to hit, damage, effects etc) are all contained in the secret paragraph, whilst only the "the goblin attacks with its shortsword" type text is actually in the normal body text.
When the attack is hovered over in the HUD, the tooltip only shows the normal body text. It would be really useful if an option can be provided to display all text, including secret text, in the tooltip, so you can see the useful information without needing to right-click the attack to bring up its item window.

(using FVTT v12.327, D&D 5e v3.2.1, Token Action HUD Core 1.5.5, TAHUD D&D 5e 1.5.7)

**Comment by Larkinabout** [comment]
Added in 1.5.8.
