### ISSUE TITLE
[BUG]Magic items module integration broke with v12

### ISSUE THREAD

**Issue by MotoMoto1234** [Larkinabout/fvtt-token-action-hud-dnd5e#110]
**Describe the bug**
The special magic item group no longer shows the spells on the item therefore the magic items group auto hides on huds

**Steps to reproduce**

**Versions:**
- Token Action HUD Core: [e.g. 0 1.0]
- Token Action HUD System: [e.g. token-action-hud-dnd5e 0.1.0]
- System: [e.g. dnd5e 2.0.3]
- Foundry VTT: [e.g. 10.291]
- Browser: [e.g. Google Chrome 108.0.5359.124]

**Additional context**
Any additional context.

**Comment by morepurplemorebetter** [comment]
What version of Token Action HUD Core are you using (you seemed to have missed that part of the bug form)?

If you are using the latest, **Token Action HUD Core v1.5.6**, than see [issue 256 of Token Action HUD Core ](https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/256).    
Commit [019cba0](https://github.com/Larkinabout/fvtt-token-action-hud-core/commit/019cba05ce154ae9d9e1f3665d9cddc9ade233df), which fixes Item Macro integration, is the reason Magic Items and Items with Spells integration is no longer working.

If you aren't using Item Macro (with Token Action HUD), then revert Core back to v1.5.5 and you get your Magic Items sections back.

**Comment by Larkinabout** [comment]
Yeah, I need to get around to fixing that. Roll back for the time being and I'll have a look when I can.

**Comment by Larkinabout** [comment]
Fixed with Token Action HUD Core 1.5.7.
