### ISSUE TITLE
[BUG] D&D5e 4.0.x: Spells HUD Element displays as `ITEM.TypeSpellPl`

### ISSUE THREAD

**Issue by hakr14** [Larkinabout/fvtt-token-action-hud-dnd5e#112]
**Describe the bug**
Spells HUD Element displays as `ITEM.TypeSpellPl`.
![ITEM.TypeSpellPl](https://github.com/user-attachments/assets/86102d8a-06f1-47a3-8b26-f60d02c5620e)

**Steps to reproduce**
1. Click on the token of an actor with prepared spells (e.g. Akra)

**Versions:**
- Token Action HUD Core: 1.5.7
- Token Action HUD System: token-action-hud-dnd5e 1.5.8
- System: dnd5e 4.0.2
- Foundry VTT: 12.331
- Browser: Google Chrome 128.0.6613.138

**Comment by Larkinabout** [comment]
I'm working on updating TAH to dnd5e 4+. There's a fee things that need fixing including those changes to the localisation paths.

**Comment by Larkinabout** [comment]
Fixed in 1.6.0.
