### ISSUE TITLE
[BUG] No letter S, customization doesn't save

### ISSUE THREAD

**Issue by mkevans80** [Larkinabout/fvtt-token-action-hud-dnd5e#118]
This has been an issue for several versions of this module, but I'm only now getting around to addressing it:

1.  It's weird, but when I attempt to edit the token bar by creating new group, the letter "S" will not input when I type it!
2.  When I customize the bar and reload the world, all saved changes are gone.

The following error appears in the console when loading the world:

<img width="388" alt="Screenshot 2024-09-24 at 4 15 46 PM" src="https://github.com/user-attachments/assets/329b25e2-4ba5-4a34-adc4-2872f4b281a2">

Versions:
- Token Action HUD Core: 1.5.7
- Token Action HUD System: 1.6.0
- System: D&D 5e v4.0.3
- Foundry VTT: version 12 build 331
- Browser: Vivaldi (Chrome-based), and Google Chrome as well.

**Comment by Larkinabout** [comment]
Weird. I'm not able to reproduce either issue. I've just created a new group called 'Something' and after reloading. It is still there. It might be useful to know what your Foundry setup is like, but also the only real way to test might be for me to hop on your instance at some point.
