### ISSUE TITLE
[FEATURE] feature subcategories

### ISSUE THREAD

**Issue by Raccoomph** [Larkinabout/fvtt-token-action-hud-dnd5e#12]
Add optionnal subcategories for Features. Would be helpfull to group maneuvers together for example. Same for Channel Divinity, Arcane Archer Arrows, etc.

![image](https://user-images.githubusercontent.com/122682880/215481973-6f5c1be4-a1f6-4411-8bb8-11648eab51e2.png)

**Comment by Larkinabout** [comment]
Added in Token Action HUD D&D 5e 1.2.0.
