### ISSUE TITLE
[BUG] Token Action HUD not showing

### ISSUE THREAD

**Issue by picollo-24** [Larkinabout/fvtt-token-action-hud-dnd5e#120]
**Describe the bug**
Module seems to not work

**Steps to reproduce**
1. Select Token
2. Nothing happens
3. See bug in console
![image](https://github.com/user-attachments/assets/5a23cf2e-75a7-4cdc-9952-9de626483703)

**Versions:**
- Token Action HUD Core: [.1.5.7]
- Token Action HUD dnd5e [1.6.0]
- System: [ dnd5e 3.3.1]
- Foundry VTT: [12.331]
- Browser: [Google Chrome 129.0.6668.59]

**Additional context**
Tried to run FInd the Culprit, and with only TAH DnD marked error still occured.

**Comment by picollo-24** [comment]
I'm dumb, I only later checked that it's for 4.X.X. Was dumbfolded bc it allowed me to activate on older DnD.

**Comment by Larkinabout** [comment]
My fault, I put a minimum version in, but messed up the structure, so it failed to do the necessary checks before updating.

**Comment by picollo-24** [comment]
Happens to the best of us. Problem solved, reverted version works, this is great module, so thanks for mantaining it!
