### ISSUE TITLE
[BUG] System maximum version

### ISSUE THREAD

**Issue by HoelFarabee** [Larkinabout/fvtt-token-action-hud-dnd5e#121]
**Describe the bug**
Despite this module being listed as compatible with "v4+", when you attempt to load it into a game world with any version higher than 4.0.0, it will gray out and not allow you to select.
![image](https://github.com/user-attachments/assets/c4ed6a21-2e93-45ed-a3c6-e7e564e248bb)

**Steps to reproduce**
1. Go to any world with dnd5e 4.0.1 or above
2. Click on manage modules
3. Scroll down to Token Action HUD D&D5e

**Versions:**
- Token Action HUD Core: 1.5.7
- Token Action HUD System: token-action-hud-dnd5e 1.6.2
- System: dnd5e 4.0.3
- Foundry VTT: e.g. 12.331
- Browser: Firefox

**Comment by PhyX-Meow** [comment]
Same here, a workaround is manually edit `4` to `4.0.99`. Also, custom-dnd5e has the exact same issue.

**Comment by Larkinabout** [comment]
Fixed in 1.6.3.
