### ISSUE TITLE
[BUG]Which versions?

### ISSUE THREAD

**Issue by ctbritt** [Larkinabout/fvtt-token-action-hud-dnd5e#122]
Not a bug per se, but confused as to which versions work on which systems. 

Asking for
- Foundry 12.331
- D&D 5e 4.03

which:
- custom dnd 5e
- token-hud-core
- token-hud-dnd5e

because right now, TAH and Custom D&D seem kind of broken in 4.0.3...

**Comment by Larkinabout** [comment]
Yeah, I messed up with the compatibility properties in the module.json as I expected it to be clever enough to work out that '4' meant all of version 4 rather than the lowest. I'll re-release when I have a second.

**Comment by Larkinabout** [comment]
Fixed in 1.6.3.

Use Token Action HUD D&D 5e 1.5.8 for dnd5e 3.3.1 and Token Action HUD D&D 5e 1.6.3 for dnd5e 4+.
