### ISSUE TITLE
[FEATURE]Old version HUD

### ISSUE THREAD

**Issue by Darkfoundry** [Larkinabout/fvtt-token-action-hud-dnd5e#123]
Where is it possible to get the old manifestos because I can't find them, neither from CORE nor from D&D

**Comment by Larkinabout** [comment]
They're here on the releases page: https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/releases or the relevant latest release for each Foundry and system version are on the package page on Foundry: https://foundryvtt.com/packages/token-action-hud-dnd5e
