### ISSUE TITLE
[BUG] HUD does not display

### ISSUE THREAD

**Issue by Nom4d-temp** [Larkinabout/fvtt-token-action-hud-dnd5e#125]
![BugReport](https://github.com/user-attachments/assets/d5a759dd-e528-467e-8353-e29ed11f8b14)

The above error comes up when clicking on a token. The HUD displays rarely and only on certain tokens - I could not determine a common property to predict the behavior.

**Versions:**
- Token Action HUD Core: 1.5.7
- Token Action HUD Sytem: token-action-hud-dnd5e 1.6.4
- System: D&D5e 4.0.4
- Foundry VTT: v12 331
- Foundry Desktop Application

**Comment by Nom4d-temp** [comment]
Sure thing. Here you go. 

![BugReport2](https://github.com/user-attachments/assets/8f642c77-8cf1-45ca-8272-094274d59d17)

Seems I may have exaggerated the bug report somewhat. It seems like the HUD didn't show up for other tokens after I clicked the warlock.

**Comment by Larkinabout** [comment]
Thanks for showing the error. It is simply an errant f that has caused all these woes.

**Comment by Larkinabout** [comment]
Fixed in 1.6.5.
