### ISSUE TITLE
[BUG] Error when applying Effect from actor features in dnd5e 4.0.x

### ISSUE THREAD

**Issue by onesockdocs** [Larkinabout/fvtt-token-action-hud-dnd5e#126]
**Describe the bug**
Attempting to apply an effect in DnD5e 4.04 causes an error and the effect does not apply.  For example, a barbarian raging will fail to apply/throw an error in the console and disrupt the application when using the dropdown menu "Effects" and clicking on 'Rage' to turn it on.

**Steps to reproduce**
Configuration: Ensure the only module loaded is Token Action Hud (Core, 5e, and lib).
1. Go to Actor Directory in the sidebar menu and click "Create Actor" 
2. Create actor with any name ("Test") and leave other settings default (Type: Player Character, Folder: blank).
3. Drag actor onto default scene.
4. Open actor character sheet (double-click on actor icon on scene).
5. Open character sheet features menu (click on features tab on the right side of character sheet).
6. Click "Add Class" button at the top of the features section.
7. Check "Barbarian" class and click select button at the bottom of the page.
8. In the popup dialog, click next through all the menus and finish.
*A clean barbarian actor with external dependencies is now created.*
9. Ensure the actor on the scene is selected.
10. Click on the 'Rage' ability in the character sheet.
11. Click on the "Use Ability" button in the popup.
12. Hover over the "Effects" menu of the Token Action Hud.  *Notice that Rage is currently not enabled.*
13. Click on 'Rage' to enable.

**Expected Results**
Rage would be enabled when the Token Action Hud button is clicked.

**Actual Results**
Rage does not enable when the Token Action Hud button is clicked.

**Additional context**
In ./scripts/roll-handler.js, the toggleEffect function is throwing an error on line 368:
`367 const effects = actor.effects.entries ? actor.effects.entries : actor.effects;`
`368 const actorEffect = effects.find(effect => effect.id === actionId);`

In this case, the "find" function does not exist on actor.effect.entries.  I am not sure if line 367 this is in place to support previous/legacy versions of foundry/dnd system, but in the current implementation the "effects" property is a collection and entries is a native function (map iterator).  To keep it backward compatible, possibly revert to a previous version:
`367 const effects = 'find' in actor.effects.entries ? actor.effects.entries : actor.effects`
Otherwise the fix seems straightforward.

**Versions:**
- Token Action HUD Core: 1.5.7
- Token Action HUD System: 1.6.3
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
Browsers:
- Brave Version 1.70.123 Chromium: 129.0.6668.89
- Edge Version 129.0.2792.79
- Firefox Version 131.0
   

update: formatting, added firefox updated version

**Comment by Larkinabout** [comment]
Fixed in 1.6.6.
