### ISSUE TITLE
[BUG] No Hud - Cannot create properties of undefined' 1.6.5

### ISSUE THREAD

**Issue by robgrahamau** [Larkinabout/fvtt-token-action-hud-dnd5e#127]
**Describe the bug**
Looks like an old bug is back again 
![image](https://github.com/user-attachments/assets/1f19a4af-7d4e-43ca-8784-41367456fa5c)
![image](https://github.com/user-attachments/assets/ac0c67e2-93ba-4059-a2b5-ec2b38764d5c)
![image](https://github.com/user-attachments/assets/1eac09ed-2edf-4820-a27d-0ada31e9bd3c)

error seems to be action-handler.js this ection
:  ```
  #isUsableItem(item) {
      return this.showUnchargedItems || item.system.uses.value || !item.system.uses.max;
    }
```
Seems to be an inventory item, I'm going through but I've a lot of inventory items on some of my players and yeah.

Was working pre 4.x

**Steps to reproduce**
when I click on a token, trying to work out what inventory item is creatiang it.


**Versions:**
- Token Action HUD Core: 1.5.7
- Token Action HUD System: dnd5e 1.6.5
- System: [e.g. dnd5e 2.0.3]  dnd5e 4.0.4
- Foundry VTT: [e.g. 10.291] 12 331
- Browser: [e.g. Google Chrome 108.0.5359.124] chrome.

**Additional context**
Any additional context.

**Comment by robgrahamau** [comment]
Ok I have narrowed this down, it appears to have something to do with Loot, specifically I removed every item from one of my players (after duplicating them) and started adding things back, the Books she is carrying as loot cause the error.. The issue though is that there is no consumable options on any of them.

I had thought maybe it was items with spells or something causing it, but I turned that off and tried again and it's still happening. Any Token that I create a generic Loot item on breaks with the above message. As seen here These two Winter Eladrin are the same except on 1 i created a 'new loot' inventory item. The moment I did break.
![image](https://github.com/user-attachments/assets/b2f6803b-0a47-4615-b92b-d188ac3bbc06)

![image](https://github.com/user-attachments/assets/0424776a-da89-4ebb-aaf7-b1bf724b5ba6)

Thing is there is nothing for Consumables in Loot items:

![image](https://github.com/user-attachments/assets/d7ad3f4f-ed1b-4764-b359-a621308a99c4)

![image](https://github.com/user-attachments/assets/579892b1-1623-4dfd-a8b1-4901cd228089)

Just to show it was working on one and not the other the hud working before it errored.

![image](https://github.com/user-attachments/assets/218625ea-9d00-4959-8b39-108ec45f9b9f)

**Comment by Larkinabout** [comment]
Does it break for you with the Starter Heroes like Randal? I'm wondering if I've not come across the issue because the starter heroes don't quite have the same structure as when creating from new. For instance, Randal has Loot items and the HUD is working for them.

**Comment by Larkinabout** [comment]
I've also just created a Loot item on a Goblin and their HUD is fine. Maybe send me the actor file?

**Comment by robgrahamau** [comment]
Will see what happens if I create an actor from start Larkin, it might be something to do with updated Actors from the previous version.

**Comment by robgrahamau** [comment]
gonna close this one as I don't think its what my chrome was reporting unless you want it open for the items with spells issue, i can't reproduce on Opera just my chrome and only that one browser making me think somethings screwy with it, the items-with-spells i've no idea on so i just turned it off and recreated the spells as actions instead.
