### ISSUE TITLE
[BUG] Rolling Saving Throws from HUD does not use or add ability modifier

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#130]
**Describe the bug**
<img width="636" alt="Greenshot 2024-10-26 11 09 09" src="https://github.com/user-attachments/assets/cf605322-b962-4ace-a4c9-778427ba8f3f">
<img width="292" alt="image" src="https://github.com/user-attachments/assets/a28f85a1-1d02-4300-a51e-ef28ccd3ab60">

When rolling the saving throw, it always rolls a saving throw without an ability modifier. Rolling a save from the character sheet works fine.

**Versions:**
- Token Action HUD Core: 2.0.1
- Token Action HUD System: dnd5e 2.0.3
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
- Browser: Google Chrome

**Comment by ShannonMcG** [comment]
<img width="623" alt="Screen Shot 2024-10-26 at 7 29 21 PM" src="https://github.com/user-attachments/assets/169d19ca-5b1d-4c28-8e07-0eee2c873d79">
I am seeing the same issue. It affects ABILITIES saving throws and ability checks from the HUD menu. The same saving throws and checks from the character sheet are correct. Other rolls from the HUD like INVENTORY and SKILLS are correct.

Versions:

1. Token Action HUD Core: 2.0.4
2. Token Action HUD System: dnd5e 2.0.1
3. System: dnd5e 4.0.4
4. Foundry VTT: 12.331
5. Browser: Google Chrome

**Comment by Larkinabout** [comment]
Fixed in 2.0.2.
