### ISSUE TITLE
[BUG] End turn missing when its actors turn, but there when not

### ISSUE THREAD

**Issue by robgrahamau** [Larkinabout/fvtt-token-action-hud-dnd5e#131]
**Describe the bug**
When its the actors turn in combat end turn vanishes 
![image](https://github.com/user-attachments/assets/9cc309cc-91c5-4762-b99c-3b62d3b90453)

however if its not your turn its visible.

![image](https://github.com/user-attachments/assets/de1ad665-995b-4758-be01-04aaa2751774)

**Steps to reproduce**
1. Start a combat encounter
2. Click on/mouse over current actors utility
3. See that End turn is missing.
4. On a person whos turn it is not see that end turn is visible
5. 
**Versions:**
- Token Action HUD Core: 2.0.4
- Token Action HUD System: 2.0.1
- System: 4.0.4
- Foundry VTT: 331
- Browser: Opera LVL6 (core: 114.0.5282.123), Chrome: 130.0.6 723.70

**Additional context**
Seemed to stop working about 2 or 3 updates ago just keep forgetting to report it.

**Comment by Larkinabout** [comment]
Fixed in 2.0.2.
