### ISSUE TITLE
[BUG] Token HUD D&D5e doesn't show Cantrips

### ISSUE THREAD

**Issue by DudeAndre** [Larkinabout/fvtt-token-action-hud-dnd5e#135]
I'm on dnd5d 4.1.1 and foundry 12.331, and my players don't have cantrips anymore in their token hud. This is also been true for previous versions of dnd5e, starting with dnd5e 4. Also I as I GM I too can't see their Cantrip in the bar.

**Comment by Larkinabout** [comment]
Check whether they are checked as Prepared and if not, try checking them. The function to add them all regardless of their Prepared setting was removed in a recent version by request.

**Comment by DudeAndre** [comment]
Thank you , it didn't cross my mind that it was about them being prepared!
