### ISSUE TITLE
[FEATURE] Do not show categories or tabs that are empty

### ISSUE THREAD

**Issue by oestred** [Larkinabout/fvtt-token-action-hud-dnd5e#16]
I noticed it shows tabs or categories that are empty.
Examples:
 A fighter shows the 'spells' tab button in the main HUD menu
 A wizard has no at will, innate, or pact spells but those all show in the list still and take up space. And also spell levels they don't have yet lists still with nothing.

Not showing empty things just gives a cleaner usage experience.

**Comment by Larkinabout** [comment]
You're probably in edit mode. Lock the HUD using the lock button that appears when you hover over the HUD.

**Comment by oestred** [comment]
You are totally right! Thank you
