### ISSUE TITLE
Add support to "Group by action type" from old module

### ISSUE THREAD

**Issue by roi007leaf** [Larkinabout/fvtt-token-action-hud-dnd5e#2]
**Describe your idea**
Add support to "Group by action type" from old module

**Versions**
- Token Action HUD System: latest
- System: dnd5e

**Additional context**
The old module had an integration with character actions 5e module and showed the HUD grouped by action types which was super useful, this new module needs that as well please!!!

**Comment by Larkinabout** [comment]
Hi @roi007leaf, is there anything missing from adding those action types using the subcategories instead?:
![token-action-hud-reactions](https://user-images.githubusercontent.com/105953297/209915180-bb416fc6-ab54-4d98-8079-f1481b6b1b8f.gif)

**Comment by roi007leaf** [comment]
It's different because when using the group by action type i still have all
the details like spell slots, spell level etc whereas using subcategories
is just plain putting the actions in a list

**Comment by Larkinabout** [comment]
I'll add the option to auto-group into default subcategories within those action-based subcategories.

In the meantime, if you'd like to keep using the new modules, you can add the same subcategories (e.g. Weapons) multiple times into categories (e.g. Actions, Bonus Actions, Favorite Actions, etc.) and remove actions you don't want to keep in those categories. That'll give you the same structure as the old module; though not much fun if you're setting up multiple actors.

**Comment by Larkinabout** [comment]
Added in release 1.0.0. This version doesn't use the 'Character Actions List' module, so you can add and remove the subcategories/actions as desired via the HUD dialogs.
