### ISSUE TITLE
[BUG] Token Action HUD dnd5e 1.2.0 does not work properly due to incorrect check of Core version

### ISSUE THREAD

**Issue by Aeristoka** [Larkinabout/fvtt-token-action-hud-dnd5e#21]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7988297/218284925-dd1778ed-3ba6-4149-b245-de548e37f922.png)

Token Action HUD doesn't load at all.

**Steps to reproduce**
1. Load into game with Token Action HUD Core 1.2.1 + Token Action HUD dnd5e 1.2.0

**Versions:**
- Token Action HUD Core: 1.2.1/1.2.0
- Token Action HUD dnd5e System: 1.2.0
- System: 2.1.4
- Foundry VTT: 10.291

**Workaround**
Revert to 1.1.x versions of Core + dnd5e System Module

**Comment by Larkinabout** [comment]
Try updating to 1.2.1. I just re-released 1.2.0 to try and fix this issue. I've no idea what caused it but 1.2.0, now 1.2.1, works if it actually manages to install.

**Comment by Aeristoka** [comment]
Updating Core to 1.2.1 absolutely fixed it!

Thanks for the quick turnaround!
