### ISSUE TITLE
[BUG] As a player, the Token HUD is correctly displayed even without token present, but clicking the buttons does nothing

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#24]
**Describe the bug**
Using the setting "Always Show HUD", the HUD is correctly displayed even if the player has no token on the scene. However, clicking any of the buttons does not result in a roll. Strangely, there is no error in the console.

**Versions:**
- Token Action HUD Core: 1.2.2
- Token Action HUD System: dnd5e 1.2.1
- System: dnd5e 2.1.4
- Foundry VTT: 10.291
- Browser: Google Chrome current

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.2.2.
