### ISSUE TITLE
[FEATURE] Ability to turn off Passive effects showing in the ability tab.

### ISSUE THREAD

**Issue by SirAron111** [Larkinabout/fvtt-token-action-hud-dnd5e#25]
**Describe your idea**
Ability to turn off Passive effects showing in the ability tab. Basically, since all class and race features show under the passive ability section in the hud it gets kinda cluttered, especially since i would only like ability to show they're relevant for combat or so. Especially for the ranger in the group, it shows like 2 active ability and like 20 passives.

![Unbenannt](https://user-images.githubusercontent.com/39855956/220898379-46223210-4425-4a90-9faa-fe289bec7a6f.PNG)

I think showing stuff like (Additional Ranger spells, Ranger archetype spellcasting and so on) basically all stuff that is unimportant tho display there should be able to be toggled off in the settings. to be honest, the passive effect section is a bit redundant anyway as most features there shouldn't show in the quick action menu but only on the chars' sheet in case it gets referenced in game.

**Comment by Larkinabout** [comment]
Hi @SirAron111, you can remove the entire 'Passive Features' subcategory or individual actions within the subcategory by using the dialogs.

**Remove the Subcategory**
1. Unlock the HUD by clicking the lock icon.
2. Right-click the 'Features' category to open the subcategory dialog.
3. Click the 'X' on 'Passive Features' in the list.
4. Click 'Accept'.
5. Lock the HUD.

**Remove Actions**
1. Unlock the HUD by clicking the lock icon.
2. Right-click the 'Passive Features' title to open the action dialog.
3. Click the 'X' on any actions in the list.
4. Click 'Accept'.
5. Lock the HUD.

**Comment by SirAron111** [comment]
Ah ok that wasnt obvious but now i know thx.
