### ISSUE TITLE
[BUG] Missing Description of the Spells

### ISSUE THREAD

**Issue by vt-tom** [Larkinabout/fvtt-token-action-hud-dnd5e#27]
**Describe the bug**
Spells Section is not correct. I think it shows the technical field.

![grafik](https://user-images.githubusercontent.com/80099175/224725992-6d1b46b7-4027-4d3c-bd54-315a440426f4.png)

**Versions:**
- Token Action HUD Core: 1.2.3
- Token Action HUD System: DnD5e 1.2.2
- System: DnD 2.1.5
- Foundry VTT: 10.291
- Browser: 110.0.54.81.180

**Comment by Larkinabout** [comment]
Hi @vt-tom, looks like it might be a holdover from when D&D 5e's system changed the language references in 2.1.0. You can fix it by either resetting the HUD using the module setting or unlocking the HUD and deleting and re-adding that category.
