### ISSUE TITLE
[BUG] Initiative for unliked token roll for all toknes from same type

### ISSUE THREAD

**Issue by rinnocenti** [Larkinabout/fvtt-token-action-hud-dnd5e#28]
**Describe the bug**
the multiple action of rolling initiative, if you used with unlinked tokens initiative is rolled for all tokens in the scene, not just selected ones.

**Steps to reproduce**
1 - place 5 unlinked tokens of the same type (unlinked tokens) in a scene.
2 - select 2 of them and roll initiative on the utility bar.
3 - the 5 tokens will have their initiative rolled instead of just the selected two.

**Versions:**
- Token Action HUD Core: 1.2.3
- Token Action HUD System: 1.2.2
- System: dnd5e 2.1.5
- Foundry VTT: 10.291

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.3.0.
