### ISSUE TITLE
[BUG] The "Show Prepared Spells only" setting blocks spells that are "always prepared" (e.g. Bards).  

### ISSUE THREAD

**Issue by rtschaefer** [Larkinabout/fvtt-token-action-hud-dnd5e#3]
I have a bard in my party and the DnD5e module for Token Action HUD has the really terrific feature to not show unprepared spells by unchecking the box. Unfortunately, when I opt for it, then the Bard's entire spell list is removed from the HUD because their spells are "Always Prepared". Hence that module feature treats those spell like they are unprepared and removes them from the HUD. 

The problem is that to get the Bard's spells to show up, I have to check the box, forcing the Cleric to have a massive wall of spells appear in his HUD, most of which are unprepared and cannot be used.

**Comment by Larkinabout** [comment]
Hi @rtschaefer, this will be fixed in the next release. Until then, you should be able to tick the 'Prepared' checkbox for those spells to show them on the HUD with the 'Show Unprepared Spells' setting unticked.

**Comment by Larkinabout** [comment]
Fixed in release 1.0.0.
