### ISSUE TITLE
[BUG] HUD isn't updated after deleting an Item from an actor programmatically

### ISSUE THREAD

**Issue by w15p** [Larkinabout/fvtt-token-action-hud-dnd5e#30]
**Describe the bug**
After deleting an item programmatically using midi-qol OnUse macros (eg `await args[0].workflow.item.delete();`), the item is deleted from the actor's inventory but still shows in the HUD.

**Steps to reproduce**
1. create item with an onUse Macro
2. delete item using midi-qol workflow
3. check actor inventory and observe that the item has been deleted
4. open the HUD and see that the item is still listed.
5. deselect the actor's token
6. reselect the actor's token
7. observe that the item has been removed from the HUD

**Versions:**
- Token Action HUD Core: 1.2.3
- Token Action HUD System: token-action-hud-dnd5e 1.2.2
- System: dnd5e 2.1.5
- Foundry VTT: 10.291
- Browser: foundry native app - mac

**Additional context**
I don't believe this is due to midi-qol as the item is being removed from actor inventory.

**Comment by w15p** [comment]
![Screenshot 2023-03-21 at 1 35 23 PM](https://user-images.githubusercontent.com/1093263/226734622-294e1f37-d8a4-44b5-ad56-a22715b8024a.png)

**Comment by Larkinabout** [comment]
Does this method of deleting an item trigger the 'deleteItem' hook? This is what Token Action HUD uses to trigger an update of the HUD.

**Comment by w15p** [comment]
It does, and when run from directly within a macro, the HUD is updated perfectly

![Screenshot 2023-04-09 at 10 34 31 PM](https://user-images.githubusercontent.com/1093263/230833549-0eb7f32e-817c-4d9f-abf3-9622e133d6e7.png)

![Screenshot 2023-04-09 at 10 34 55 PM](https://user-images.githubusercontent.com/1093263/230833553-3a07425d-5c47-45ef-8e6f-4bd9d4aae903.png)

 I'm running it in a module static class method though and that's where I was seeing the issue.

Regardless - it is not a bug in in the HUD - thanks for looking into it.
