### ISSUE TITLE
[BUG] New conditions added via Combat Utility Belt's Condition Lab are not sorted automatically

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#33]
**Describe the bug**
After adding a new condition via Combat Utility Belt's Condition Lab, the new condition is not automatically sorted alphabetically in the token action hud.

Please see this screenshot, where the condition "Starry Form" was recently added and is not sorted correctly.

The sorting works when deleting the conditions category from the hud and re-adding it, but this is very annoying to do every time.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/72390280/230095007-8b24ab76-a414-4904-ba0a-bb4b9f44959a.png">

**Steps to reproduce**
1. Create condition in condition lab.
2. Sort conditions alphabetically in condition lab.
3. New condition will always be last in token action hud.

**Versions:**
Current versions of Foundry, 5e system and all modules

**Comment by nschoenwald** [comment]
Does the order of actions get synced when using the macro? Because then I could just drag the actions in my hud and then sync it to all the players.

**Comment by nschoenwald** [comment]
I just tried to reorder the conditions and I can't do it manually. I can change the order of the subcategories, but that's not what this issue is about. It's about the order of the conditions themselves. In the screenshot, you can see that the newly created "Starry Form" condition is at the end, but it should be sorted alphabetically. I can't drag the condition itself to the correct place.

**Comment by Larkinabout** [comment]
Are you sorting conditions like this?:

![token-action-hud-sort-actions](https://user-images.githubusercontent.com/105953297/230369485-7e4280b0-e246-47aa-b811-6c47ec8d0b96.gif)

**Comment by nschoenwald** [comment]
Oh, thank you for the clarification! I was clicking the "Conditions" button, not the heading.
Sorting it like that works, but it seems to me like the changes are per token, right? How would I sync it to all tokens and players?

**Comment by Larkinabout** [comment]
Ah, yes, it is per actor. Maybe we need an auto-sort button in the future to allow users to sort alphabetically as needed, but without overriding the ability to sort as desired.

**Comment by nschoenwald** [comment]
Yes, that would be perfect and greatly reduce the amount of work needed for adding a condition.

**Comment by Larkinabout** [comment]
Larkinabout/fvtt-token-action-hud-core#85
