### ISSUE TITLE
Installing on The Forge

### ISSUE THREAD

**Issue by DarkkingDraco** [Larkinabout/fvtt-token-action-hud-dnd5e#39]
This might be a Forge issue, but prior to the update a had this module installed. Now it appears to be uninstalled and any time I try to install this version or an older version I get this message.:

**Failed to install module: EACCES: permission denied, stat '/forge-vtt/bazaar/modules/token-action-hud-dnd5e/1.4.1/languages'**

**Comment by Larkinabout** [comment]
Looking at the messages over on The Forge Discord, it looks like it was an issue with The Forge, which is now fixed.
