### ISSUE TITLE
[FEATURE] Looser filter for Reactions for Midiqol Users

### ISSUE THREAD

**Issue by MotoMoto1234** [Larkinabout/fvtt-token-action-hud-dnd5e#41]
**Describe your idea**
When you setup a group filter for Reactions, its only reading the core action type "Reaction".  In Midiqol, theres 3 other reaction action types.  I will share the image in the additional context.  Right now we can manually add the others in as individual items but its non optimal.  I guess we just need for the filter for that to search for anything in that category with the word "Reaction".  

**Versions**
- Token Action HUD System: dnd5e 1.4.1
- System: dnd5e+midiqol

**Additional context**
![image](https://user-images.githubusercontent.com/116308065/237048291-f6a86208-c325-4ebf-ba5b-a48fcfa9ca74.png)

**Comment by Larkinabout** [comment]
Added in Token Action HUD D&D 5e 1.4.2.
