### ISSUE TITLE
[BUG] legendary actions not populating in the hud

### ISSUE THREAD

**Issue by modzy2** [Larkinabout/fvtt-token-action-hud-dnd5e#42]
**Describe the bug**
Legendary actions are not populating in the HUD, also they can't be added manually as far as I can tell.

**Steps to reproduce**
1. Import a Kraken from the SRD compendium
2. Drag a kraken onto the canvas
3. Edit the hud and add "Group: Legendary Actions" to a chosen tab group
4. Note that Legendary Actions group heading appears (while in hud edit) but with no actions under it
5. right click the legendary actions group in the menu while in edit mode
6. try to add (for example) the Ink Cloud action, but it won't show up in search

**Versions:**
- Token Action HUD Core: 1.4.4
- Token Action HUD System:  token-action-hud-dnd5e 1.4.2
- System: dnd5e 2.1.5
- Foundry VTT: 10.291
- Browser: Google Chrome Version 113.0.5672.93 (Official Build) (64-bit)

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.3.
