### ISSUE TITLE
[BUG] Charges for items are displayed twice

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#46]
**Describe the bug**
See Wand of Secrets in this screenshot:
<img width="208" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/72390280/faa630cc-e0c3-4167-a491-affb4f745857">
<img width="701" alt="image" src="https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/72390280/c30d46e3-df3b-417b-8cf1-764c4a13b5f3">

**Versions:**
Latest version of the modules, using last version of Foundry V10 and Dnd5e system 2.1

**Comment by Larkinabout** [comment]
Is it still duplicated with all other modules disabled?

**Comment by nschoenwald** [comment]
I just tested it and yes, even with all other modules disabled, the same error occurs.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.5.
