### ISSUE TITLE
[BUG] Token hud does not appear for monsters with spells when "show uneqipped items" is selected

### ISSUE THREAD

**Issue by miri10134** [Larkinabout/fvtt-token-action-hud-dnd5e#5]
**Describe the bug**
When selecting a monster that has spells while the setting "show unequipped items" is selected, the token hud does not appear and an error is logged to the console:

![image](https://user-images.githubusercontent.com/57747482/213533915-b055497c-3171-4752-a2c2-f054c871a9af.png)

**Steps to reproduce**
1. Set "Show unequipped items" to true in the module settings.
2. Put any monster with spells on the field (like the Acolyte from the compendium)
3. Select the monster's token
4. The token hud does not appear
5. Open browser console for error.

**Fix**
This can easily be fixed by changing line 1219 of the action-handler.js file from "return" to "return spells".

However, it seems weird that "show unequipped items" is checked on that line in the first place. 

**Versions:**
- Token Action HUD Core: 0 1.1
- Token Action HUD System: token-action-hud-dnd5e 0.1.2
- System: dnd5e 2.1.1
- Foundry VTT: g. 10.291
- Browser: MS Edge 109.0.1518.55

**Comment by Larkinabout** [comment]
It looks like I've inadvertently fixed this one while overhauling the code for release 1.0.0. Thanks for letting me know.

**Comment by Larkinabout** [comment]
Fixed in release 1.0.0.
