### ISSUE TITLE
[BUG] Deselecting a condition under the "Effects" menu does deselect it on the PC, but it remains on the Effects menu

### ISSUE THREAD

**Issue by brother-oak** [Larkinabout/fvtt-token-action-hud-dnd5e#51]
**Describe the bug**
If I add a condition to a PC using the Conditions tab, it adds fine, and appears in the "Effects" tab as expected.
If I remove the condition from the Conditions tab, it gets removed from the PC and no longer appears in the Effects tab, and is deselected in the Conditions tab, as expected.

However, if I remove the condition using the Effects tab, it doesn't work completely. It correctly removes the condition from the PC (removes the icon and the PC no longer has the condition), but the condition still appears (deselected) under the Effects tab, and remains *selected* in the conditions tab.  If I then re-select it in Effects, it will re-apply the condition. If I re-select it in Conditions, it will do nothing to the PC, but will deselect the condition text in Conditions and remove it completely from Effects.

This doesn't seem to be correct, as it is confusing and inconsistent.

I used to use the older version of this module, under Foundry v10, and that would remove the condition correctly if selected from either the Condition tab or the Effects tab. I presume that is how this should work?

**Steps to reproduce**
1. Select a player token
2. In the Conditions tab, apply a condition (e.g. poisoned). Everything applied correctly
3. In the Effects tab, deselect the poisoned condition. Poisoned condition correctly removed from the PC but poisoned text remains (deselected) in the Effects tab, and is still selected in the Conditions tab

**Versions:**
Foundry v11.302
D.D 5e version v2.2.1
TA HUD Core version v1.4.9
TH HUD 5e version v1.4.5
Browser Chrome 114.0.5735.134 (Official Build) (64-bit)

**Comment by ssg3Davins** [comment]
It is intended, left click->disable effect, right click->delete effect

**Comment by brother-oak** [comment]
Ah - didn't realise that. Apologies.

In which case the bug is (I think) that when the effect is disabled using the Effects tab, it is still shown as enabled under the Conditions tab

It also seems a little inconsistent, as using left or right click under the Conditions tab both delete from the Effects tab (but if that is as intended, so be it - the module is useful enough that I can live with a bit of inconsistency!)

**Comment by Larkinabout** [comment]
> In which case the bug is (I think) that when the effect is disabled using the Effects tab, it is still shown as enabled under the Conditions tab

Yeah,  that is a bug.

> It also seems a little inconsistent, as using left or right click under the Conditions tab both delete from the Effects tab (but if that is as intended, so be it - the module is useful enough that I can live with a bit of inconsistency!)

As the Effects group serves other effects aside from conditions, I wanted the left-click to be the least destructive. I think some actions could do with a reminder on hover over about what either click will do.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.6.
