### ISSUE TITLE
[BUG] Conditions & DFred's Displaying incorrectly

### ISSUE THREAD

**Issue by Tatonker** [Larkinabout/fvtt-token-action-hud-dnd5e#52]
**Describe the bug**
Conditions listed in the Conditions tab display incorrectly and show as 'Undefined' and do not respect the grid selection for the category.

**Steps to reproduce**
1. Install the TAH modules listed below as well as Dfreds Conventient Effects 5.0.3
2. Click on the 'Conditions' tab of TAH 

**Versions:**
- Token Action HUD Core: 1.4.10
- Token Action HUD System: token-action-hud-dnd5e 1.4.6
- System: dnd5e 2.2.1
- Foundry VTT: 11.304
- Browser: Google Chrome 114.0.5735.199

**Additional context**
![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/70360365/238c4e7a-0f3d-4481-a9b1-0e3d9d0cc385)

Any additional context.
I am pretty sure this worked properly before yesterday's release. Without DFred's CE the default Conditions display correctly.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.7.
