### ISSUE TITLE
[FEATURE] TAH not picking up Dfred CE's effects.

### ISSUE THREAD

**Issue by ctbritt** [Larkinabout/fvtt-token-action-hud-dnd5e#53]
**Describe the bug**
Not applying or removing DFred's CE, like blindness, deafness, or invisible, via TAH
 
**Steps to reproduce**
1. Using TAH and Dfred's in either Add or Replace mode, try to apply condition that affects the canvas, such as Blinded, Deafened, or Invisible. 
2. The visual effect doesn't happen. 
3. Use TAH to apply core Foundry effect for Blind, Deaf or Invisible.
4. It works

**Versions:**
- Token Action HUD Core: 1.4.11
- Token Action HUD System: token-action-hud-dnd5e 1.4.7
- System: dnd5e 2.2.1
- Foundry VTT: 11.304
- Browser: Chrome

**Additional context**
Here are screen shots. 

Blindess applied with Df CE panel with vision 5e active:
![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/4516034/acbfa42f-8634-48d1-929c-9287694f0a9a)

after clicking Blinded on TAH to remove it:
![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/4516034/4d7e7983-8de3-4ba4-b877-70645e4b80f3)

here's some additional context, maybe: https://github.com/DFreds/dfreds-convenient-effects/issues/253

**Comment by Larkinabout** [comment]
Added in Token Action HUD D&D 5e 1.4.8.
