### ISSUE TITLE
[BUG] Can't Reorganize HUD Elements

### ISSUE THREAD

**Issue by tartarts** [Larkinabout/fvtt-token-action-hud-dnd5e#57]
_When I try to reorganize the various Action lists within the module, it immediately reverts after I hit 'Save', Here are some screenshots of me trying to get the Spells in a specific order for a Warlock character._ **This was reproduced with no modules except TAHUD and its dependencies.**

![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/114840468/fe60d3fc-39bb-4ddc-96df-1f42d46bfa97)
Disorganized HUD, with Consumables inbetween Spell tiers.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/114840468/deacdff3-8932-4619-8a9f-2363538d8cbe)
I reorganize and hit Accept

![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/114840468/f75ed106-1966-4964-92fa-b6fd9401a1b6)
Some elements seem to move but others arbitrarily appear in strange places. When I check back in the organizing dialogue, it shows the bugged location too.

- Token Action HUD Core 1.4.11
- Token Action HUD dnd5e 1.4.8
- System: dnd5e 2.2.2
- Foundry VTT: 11.305
- Browser: Opera GX

**Comment by Larkinabout** [comment]
Can you please send me the files from your **Data/token-action-hud-core/world/** folder?

**Comment by Larkinabout** [comment]
If this is still an issue, let me know.
