### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by orcnog** [Larkinabout/fvtt-token-action-hud-dnd5e#58]
**Describe the bug**
Error: An error occurred while rendering TokenActionHud 41. One of original or other are not Objects! _(directly from the console)_

**Steps to reproduce**
1. New world, no other modules installed.
2. Click on a token to see the error in the console.
3. Hover on any of the HUD top-level menu items to see the dropdown menus stay open forever.

**Versions:**
- Token Action HUD Core: 0 1.4.13
- Token Action HUD System: token-action-hud-dnd5e 0.4.9
- System: dnd5e 2.2.2
- Foundry VTT: 11.305
- Browser: native app

**Additional context**

[token-action-hud-5e-error-on-click-and-on-hover.webm](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/70491549/49c7d693-d126-46d4-bdac-c000364abf30)

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD 1.4.14.
