### ISSUE TITLE
[BUG] Magic Item spells not showing

### ISSUE THREAD

**Issue by YakFromStateFarm** [Larkinabout/fvtt-token-action-hud-dnd5e#59]
There is an issue currently with spells on items from the Magic Items module not showing up in the HUD. This is because the old module seems to no longer be supported, and the new version has been worked on by a new dev and slightly renamed. It used to be "magicitems" and is now "magic-items-2". I have forked this branch and made some changes that seem to fix the issue. Will make a PR for that right after, but wanted to have the bug noted in dev notes.

**Comment by Larkinabout** [comment]
Added in Token Action HUD D&D 5e 1.4.11.
