### ISSUE TITLE
[BUG] Pact Magic are not shown under "spells"

### ISSUE THREAD

**Issue by Raccoomph** [Larkinabout/fvtt-token-action-hud-dnd5e#6]
as titled

**Versions:**
- Token Action HUD Core most recent
- Token Action HUD System dnd5e most recent
- System: dnd5e most recent
- Foundry VTT: most recent stable

**Comment by Larkinabout** [comment]
Fixed in release 1.0.0. You may need to add the subcategory for pact spells using the subcategory dialog (unlock the HUD and right-click a button on the top row).
