### ISSUE TITLE
[BUG] Effects disappear from HUD when effects are added to or removed from character sheet

### ISSUE THREAD

**Issue by daevadragon** [Larkinabout/fvtt-token-action-hud-dnd5e#61]
**Describe the bug**
When I add an effect to a character sheet, the buttons in the effect category are removed from the token action hud

**Steps to reproduce**
1. Add an effect to a character
2. Select that characters token
3. Click on the effect tab of the action hud
4. See no buttons for the effects available to the character

**Versions:**
- Token Action HUD Core: 1.4.16
- Token Action HUD System: token-action-hud-dnd5e 1.4.9
- System: dnd5e 2.2.2
- Foundry VTT: 10.303
- Browser: Google Chrome 115.0.5790.99

**Additional context**
Reloading the application makes the effect buttons reappear. 
Adding a new category to the hud that includes the effects groups does not act differently than the standard effects category, and if the game is on a load that is corrupted in this way, the new category maintains that corruption.

**Comment by daevadragon** [comment]
It also appears that it is not character unique. Once an effect has been added to any character, I cannot see the buttons that should be available to any other character

**Comment by danzchen7** [comment]
I encountered this exact same issue but on Version Release 11.306

Tested using the Foundry VTT app as GM, and both Chrome and Firefox browsers while signed in as Player.

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD D&D 5e 1.4.10.
