### ISSUE TITLE
[FEATURE] Show bonuses for checks and saving throws

### ISSUE THREAD

**Issue by nschoenwald** [Larkinabout/fvtt-token-action-hud-dnd5e#63]
**Describe your idea**
Skill checks show the bonus next to the name, plain ability checks or saving throws do not. It would be great if they would also show the bonuses.

![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/72390280/169abd13-5afe-437a-8f58-4fe0095ac69e)

**Comment by Larkinabout** [comment]
Added in Token Action HUD D&D 5e 1.4.11.
