### ISSUE TITLE
[BUG] Inconsistent Zero Value Bonus Formatting for Skills, Abilities, and Saving Throws

### ISSUE THREAD

**Issue by Red5MT** [Larkinabout/fvtt-token-action-hud-dnd5e#66]
When the bonus for skills, abilities, and saving throw is 0 (zero), the formatting is inconsistent across Player and NPC tokens.

For PCs, zero value Group: Skills displays '+0'
For PCs, zero value Group: Saving Throws displays nothing'
For PCs, zero value Group: Abilities displays '0'

For NPCs, zero value Group: Skills displays nothing.
For NPCs, zero value Group: Saving Throws displays nothing.
For NPCs, zero value Group: Abilities displays '0'

Although this is a very minor 'issue', I assume you would like them to be consistent. I would think most would prefer '+0'.

![SkillsMonster](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/83143296/ec001f44-a495-43ad-86f2-a39730e3072e)
![SkillsPlayer](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/83143296/83e5385d-fff1-4dee-96b0-4c9a05d101c7)

Thanks again for a fantastic module!

**Comment by Larkinabout** [comment]
Fixed in Token Action HUD Core 1.4.19.
