### ISSUE TITLE
[BUG] Translation error

### ISSUE THREAD

**Issue by lucaspicerni** [Larkinabout/fvtt-token-action-hud-dnd5e#67]
Hello! The Token Action HUD D&D 5e is not respecting the translation file (I tested it with the Portuguese language) in some sections. From what I've found, it's happening with active and passive features, spell levels, innate, at-will, and pact spellcasting. Check out the example where my Foundry is using PT-BR but the text appears in EN:

![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/95550238/0ab5efd3-2c74-420a-8087-68c0c56ac5a3)

**Versions:**
- Token Action HUD Core: 1.4.18
- Token Action HUD D&D 5e: 1.4.11
- D&D 5e: 2.3.0
- Foundry VTT: 10.303
- Browser: Chrome 116.0.5845.111 x64

**Comment by Larkinabout** [comment]
It looks like we don't currently have translations for those in the BR language file. If you're able to provide translation, please update this file and attach it here: https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/blob/main/languages/br.json

**Comment by lucaspicerni** [comment]
Of course, I can provide the translation! However, as I said, the Token Action HUD D&D 5e is not fully considering the translation file. I have completed the translation of the file you indicated, locally, and there are still parts of the module that are not being translated correctly, as I mentioned before.
