### ISSUE TITLE
[BUG] - Error in unlkinked NPCs

### ISSUE THREAD

**Issue by rinnocenti** [Larkinabout/fvtt-token-action-hud-dnd5e#69]
**Describe the bug**
![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/3178127/007630c6-89cf-409b-b8d0-d3b3b7b91347)

**Steps to reproduce**
1. Have a token from a unlink actor (Npc)
2. Click on token

**Versions:**
- Token Action HUD Core: 1.4.22
- Token Action HUD System: [e.g. token-action-hud-dnd5e 1.4.14
- Foundry VTT: 11.313

**Comment by Larkinabout** [comment]
Fixed in 1.4.15.
