### ISSUE TITLE
[BUG] Pact Magic don't show

### ISSUE THREAD

**Issue by Kharmans** [Larkinabout/fvtt-token-action-hud-dnd5e#76]
**Describe the bug**
Pact Magic spells are not showing on hud.

**Versions:**
- Token Action HUD Core: v1.5.4
- Token Action HUD System D&D 5e: v1.5.3
- D&D5e: v3.1.0
- Foundry VTT: v11.315
- Browser: OperaGX LVL5 (core: 107.0.5045.75)

**Additional context**
I already have the Pact Spell add on hud, but nothing is showed.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/112586547/8702b47e-bd48-499c-afb8-43c851ed14ba)

**Comment by Larkinabout** [comment]
Using the Starter Hero, Sefris, the pact spells are showing for me. Do you have spell slots available under Pact Magic?
![image](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/assets/105953297/85daccb8-fa40-4bfe-99e9-565a1f3f6756)

**Comment by Larkinabout** [comment]
Also, make sure you don't just have the Pact Spells group minimised.

**Comment by Kharmans** [comment]
Okay, I doesn't have any spell slots for Pact Spells.
I'm sorry for that and thanks!
