### ISSUE TITLE
[FEATURE] Tidy 5e Sheets custom sections integration

### ISSUE THREAD

**Issue by kgar** [Larkinabout/fvtt-token-action-hud-dnd5e#87]
**Describe your idea**
From a user in the Tidy discord community:
> This is probably a long-shot, but would merge the best of two worlds, if ist even doable.
>
> We use [Token Action HUD from Larkinabout](https://github.com/Larkinabout/fvtt-token-action-hud-core), which is great. Its biggest downside is that grouping is limited to a couple of presets.
>
> If it would somehow be possible for this HUD to group items/spells per section instead of per preset-group, that would be awesome!

With this idea in mind, I'd like to discuss the possibility of collaborating to make this feature happen.
I am open to writing integration code on my side, since it would deal with flags on my sheets, and I also can provide information if you're interested in integrating on this side.
I haven't been able to look as closely as I'd like, but is there an API that could be used to accomplish what they're asking?

**Versions**
- Token Action HUD System: token-action-hud-dnd5e
- System: dnd5e

**Additional context**
N/A

**Comment by morepurplemorebetter** [comment]
### Clarification
I'm the one who made the original feature request on kgar's Discord. Apologies for writing "limited to a couple of presets". What I meant is that the groups are pre-determined, which is limiting when the tidy5e character sheet now offers dynamic grouping that the player can control. The discrepancy between how things are grouped on the sheet and how they are grouped in the action HUD is what I'm trying to address. I see that this will mostly depend on kgar to implement, which will be hard without documentation, so hopefully the [file that integrates the Magic Items module](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/blob/main/scripts/magic-items-extender.js) is enough to build upon.

### Thanks
Regardless, thanks for all the work that you are doing, this is a great module and has made playing on FoundryVTT so much easier!

### Hide items from HUD
In a related question, how would one dynamically remove an item (spells specifically) from showing up in the HUD completely (or just for the player, but visible for the GM)? I'm trying to hide spells gained from items when the item is not yet identified. This is regarding the Spells with Items module, so unlike Magic Items, the spells are regular items owned by the actor.
**Is their a flag that could set on the spell? Or would this be its own feature request?**

**Comment by kgar** [comment]
So, I think at this point, I have the info for having a go at implementing something for Tidy.
I'll keep the issue open on my repo and update it to indicate that I'll be doing something on my side to hook into Token Action HUD's API.

Thanks for the rad module. My players and I depend on and love Token Action HUD!
