### ISSUE TITLE
[BUG] Spell data (components, concentration, ritual) is not showing

### ISSUE THREAD

**Issue by morepurplemorebetter** [Larkinabout/fvtt-token-action-hud-dnd5e#90]
### Describe the bug
The spell data is no longer showing when "Display Spell Information" is enabled. This used to work in older DnD5e versions (or older HUD versions, I didn't check). I'm referring about the components, concentration, and ritual letters.

### Steps to reproduce
Enable "Display Spell Information" and don't see any actual information added to spells.

### Versions
- Token Action HUD Core: v1.5.5
- Token Action HUD D&D 5e: v1.5.5
- System: DnD5e v3.1.2
- Foundry VTT: FoundryVTT v11.315
- Browser: Mozilla Firefox 126.0.1 (64-bit)

**Comment by Larkinabout** [comment]
Fixed in 1.5.6.
