### ISSUE TITLE
[BUG] Item charges not displaying for consuming attributes

### ISSUE THREAD

**Issue by morepurplemorebetter** [Larkinabout/fvtt-token-action-hud-dnd5e#91]
### Describe the bug
Charges for an item are correctly displayed when set to consume other items, or charges of other items, but not when set to consume an attribute.

### Steps to reproduce
Set an item to consume an attribute (e.g. resources.primary).

### Versions
- Token Action HUD Core: v1.5.5
- Token Action HUD D&D 5e: v1.5.5
- System: DnD5e v3.1.2
- Foundry VTT: FoundryVTT v11.315
- Browser: Mozilla Firefox 126.0.1 (64-bit)

**Comment by Larkinabout** [comment]
Fixed in 1.5.6.
