### ISSUE TITLE
[BUG] Item limited uses visible even when "none" is selected

### ISSUE THREAD

**Issue by morepurplemorebetter** [Larkinabout/fvtt-token-action-hud-dnd5e#92]
**Describe the bug**
A description of the bug and any screenshots.

**Steps to reproduce**
1. Select an item and set the available and maximum limited uses to something (e.g. 2 of 5 charges).
2. Now change the option for limited uses to "none", which hides the available and maximum uses.
3. The HUD still displays the numbers.

### Versions
- Token Action HUD Core: v1.5.5
- Token Action HUD D&D 5e: v1.5.5
- System: DnD5e v3.1.2
- Foundry VTT: FoundryVTT v11.315
- Browser: Mozilla Firefox 126.0.1 (64-bit)

**Comment by Larkinabout** [comment]
Fixed in 1.5.6.
