### ISSUE TITLE
[BUG] Unidentified items show full (identified) description/details in tooltip

### ISSUE THREAD

**Issue by morepurplemorebetter** [Larkinabout/fvtt-token-action-hud-dnd5e#94]
### Describe the bug
When an item is marked as unidentified, a player can only see its "unidentified" description and none of its details. However, using the HUD, the full description and a digest of its details appears in the tooltip.

### Steps to reproduce
1. Set the HUD Core setting "Tooltip Display" to "Full Tooltip"
2. Hover over an unidentified item in the HUD
3. See the description show up, even as a player, while that description isn't visible 

### Versions
- Token Action HUD Core: v1.5.5
- Token Action HUD D&D 5e: v1.5.5
- System: DnD5e v3.1.2
- Foundry VTT: FoundryVTT v11.315
- Browser: Mozilla Firefox 126.0.1 (64-bit)

**Comment by Larkinabout** [comment]
Fixed in 1.5.6.
